// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("exports dojo/_base/lang dojo/_base/array dojo/_base/html dojo/has dojo/Deferred jimu/utils esri/tasks/QueryTask esri/tasks/support/Query".split(" "),function(f,w,p,u,t,r,q,x,y){f.exportCSV=function(c,d,b){return f._createCSVStr(d,b).then(function(a){return f._download(c+".csv",a)})};f.exportCSVFromFeatureLayer=function(c,d,b){b=b||{};return f._getExportData(d,{datas:b.datas,fromClient:b.fromClient,outFields:b.outFields,filterExpression:b.filterExpression}).then(function(a){return f._formattedData(d,
a,{formatNumber:b.formatNumber,formatDate:b.formatDate,formatCodedValue:b.formatCodedValue}).then(function(h){return f.exportCSV(c,h.datas,h.columns)})})};f.exportCSVByAttributes=function(c,d,b,a){a=w.mixin({},a);a.datas=b;return f.exportCSVFromFeatureLayer(c,d,a)};f.exportCSVByGraphics=function(c,d,b,a){b=p.map(b,function(h){return h.attributes});return f.exportCSVByAttributes(c,d,b,a)};f._createCSVStr=function(c,d){var b=new r,a="",h=0,g=0,e="",k="";try{p.forEach(d,function(m){a=a+e+m;e=","});a+=
"\r\n";h=c.length;g=d.length;for(var n=0;n<h;n++){e="";for(var l=0;l<g;l++)(k=c[n][d[l]])||"number"===typeof k||(k=""),k&&/[",\r\n]/g.test(k)&&(k='"'+k.replace(/(")/g,'""')+'"'),a=a+e+k,e=",";a+="\r\n"}b.resolve(a)}catch(m){console.error(m),b.resolve("")}return b};f._isIE11=function(){return 11===q.has("ie")};f._isEdge=function(){return q.has("edge")};f._getDownloadUrl=function(c){return window.Blob&&window.URL&&window.URL.createObjectURL?(c=new Blob(["\ufeff"+c],{type:"text/csv"}),URL.createObjectURL(c)):
"data:attachment/csv;charset\x3dutf-8,\ufeff"+encodeURIComponent(c)};f._download=function(c,d){var b=new r;try{if(t("ie")&&10>t("ie")){var a=window.top.open("about:blank","_blank");a.document.write("sep\x3d,\r\n"+d);a.document.close();a.document.execCommand("SaveAs",!0,c);a.close()}else if(10===t("ie")||f._isIE11()||f._isEdge()){var h=new Blob(["\ufeff"+d],{type:"text/csv"});navigator.msSaveBlob(h,c)}else{var g=u.create("a",{href:f._getDownloadUrl(d),target:"_blank",download:c},document.body);if(t("safari")){var e=
document.createEvent("MouseEvents");e.initEvent("click",!0,!0);g.dispatchEvent(e)}else g.click();u.destroy(g)}b.resolve()}catch(k){b.reject(k)}return b};f._getExportData=function(c,d){var b=new r,a=null,h=d.datas;a=d.outFields;a&&a.length||(a=c.fields);h&&0<h.length?b.resolve({data:h||[],outFields:a}):d.fromClient?(h=p.map(c.graphics,function(g){return g.attributes}),b.resolve({data:h||[],outFields:a})):f._getExportDataFromServer(c,a,d).then(function(g){b.resolve({data:g||[],outFields:a})});return b};
f._getExportDataFromServer=function(c,d,b){var a=new r;if("esri.layers.FeatureLayer"!==c.declaredClass)return a.resolve([]),a;var h=new x(c.url),g=new y;g.where=b.filterExpression||c.getDefinitionExpression&&c.getDefinitionExpression()||"1\x3d1";0<d.length?(c=p.map(d,function(e){return e.name}),g.outFields=c):g.outFields=["*"];g.returnGeometry=!1;h.execute(g,function(e){e=p.map(e.features,function(k){return k.attributes});a.resolve(e)},function(e){console.error(e);a.resolve([])});return a};f._formattedData=
function(c,d,b){var a=new r,h=[],g=d.data;d=d.outFields;for(var e=0,k=g.length;e<k;e++){for(var n={},l=0;l<d.length;l++){var m=d[l];n[m.alias||m.name]=f._getExportValue(g[e][m.name],m,c.objectIdField,c.typeIdField,g[e][c.typeIdField],c.types,b)}h.push(n)}c=p.map(d,function(v){return v.alias||v.name});a.resolve({datas:h,columns:c});return a};f._getExportValue=function(c,d,b,a,h,g,e){var k=!!d.domain&&e.formatCodedValue;e="esriFieldTypeDate"===d.type&&e.formatDate;var n=b&&d.name===b;a=a&&d.name===
a;return e?q.fieldFormatter.getFormattedDate(c):a?q.fieldFormatter.getTypeName(c,g):k?q.fieldFormatter.getCodedValue(d.domain,c):k||e||n||a?c:(k=null,b&&g&&0<g.length&&(b=(b=p.filter(g,function(l){return l.id===h}))&&b[0])&&b.domains&&b.domains[d.name]&&b.domains[d.name].codedValues&&(k=q.fieldFormatter.getFormattedCodedValue(b.domains[d.name],c)),null!==k?k:c)}});